name: AWS Resource Creation
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  Deploy_CFT: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v2
        
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name MyEMRStack \
            --template-file .github/workflows/MYcft2.yaml \
            --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          EC2_KEY_PAIR_PATH: s3://requiredfiles2323/onekey.pem
      
      - name: Start Crawler
        run: |
          aws glue start-crawler --name data-crawler
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
